### ISSUE TITLE
Don't disable env checker

### ISSUE THREAD

**Issue by inpefess** [inpefess/gym-saturation#79]
Current implementation of the default environment checker from `gym` supposes that observations are `numpy` compatible https://github.com/openai/gym/blob/a5afdb3f7a976e86c88ca7368bf57f0a1f496f76/gym/utils/passive_env_checker.py#L252

Maybe we can add a checker of our own or find another workaround since having checker per se is a good idea.

**Comment by inpefess** [comment]
Might be related to this PR https://github.com/openai/gym/pull/2903

**Comment by pseudo-rnd-thoughts** [comment]
Hi, in the new environment checker (for release v0.25.0) there will be a new argument in `EnvSpec` when you register your environment that can by default disable the environment checker if you wished to use your own environment checker that is customise for your uses. 
For interest, what was the issue with the environment checker as a number of critical error were found with the checker that are fixed in https://github.com/openai/gym/pull/2903 so could you test again that there aren't any unexpected warnings

**Comment by inpefess** [comment]
> For interest, what was the issue with the environment checker as a number of critical error were found with the checker that are fixed in [openai/gym#2903](https://github.com/openai/gym/pull/2903) so could you test again that there aren't any unexpected warnings

Thank you, @pseudo-rnd-thoughts! With your branch, I can do without disabling checks and with no errors since you check only observations of pre-defined classes, not assuming anything about other ones.

In my case, the observations are formal language statements (represented as nested JSON-like structures), which are afterwards embedded (using Wrappers) to some `numpy` arrays as users need fit.
